export const addTodo = 'ADD_TODO'
export const removeTodo = 'REMOVE_TODO'
export const doTodo = 'DO_TODO'
export const filterAllTodo = 'FILTER_ALL_TODO'
export const filterCompeleteTodo = 'FILTER_COMPELETE_TODO'
export const filterIncompeleteTodo = 'FILTER_INCOMPELETE_TODO'